version: '3.0'
services:
  test_db:
    container_name: test_db_connection
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: my_db
    ports:
      - "5438:5432"